version: '3.8'

services:
  airbnb-pipeline:
    build: .
    container_name: airbnb_pipeline
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./report:/app/report
    command: python src/main.py